#!/usr/bin/env node
/**
 * AID PoC Transpiler — .aid → Rust/Axum
 * 
 * This is a proof-of-concept string-based transpiler.
 * It handles the hello-world subset of AID:
 * - module declaration
 * - use std.http
 * - server creation with port
 * - server.get() routes with Response.text() and Response.json()
 * - server.start()
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';

const aidFile = process.argv[2];
const outDir = process.argv[3] || './build/rust-gen';

if (!aidFile) {
  console.error('Usage: node transpile.mjs <file.aid> [output-dir]');
  process.exit(1);
}

console.log(`  ✓ Reading ${aidFile}`);
const source = readFileSync(aidFile, 'utf-8');
const lines = source.split('\n').map(l => l.trim()).filter(l => l && !l.startsWith('//'));

// ── Parse (minimal) ──────────────────────────────────────

let moduleName = 'main';
let port = 8080;
const routes = [];

// Extract module name
const moduleLine = lines.find(l => l.startsWith('module '));
if (moduleLine) moduleName = moduleLine.replace('module ', '').trim();

// Extract port
const portMatch = source.match(/http\.new\(port:\s*(\d+)\)/);
if (portMatch) port = parseInt(portMatch[1]);

// Extract routes — regex-based for PoC
// Match routes — use a more flexible approach for multi-line bodies
const routeRegex = /server\.(get|post|put|patch|delete)\("([^"]+)"\)\s*=>\s*fn\((\w+)\)\s*->\s*Response\s*\{([\s\S]*?)\n\s{4}\}/g;
let match;
while ((match = routeRegex.exec(source)) !== null) {
  const [, method, path, reqParam, body] = match;
  
  let responseType, responseBody;
  
  const textMatch = body.match(/Response\.text\("([^"]+)"\)/);
  const jsonMatch = body.match(/Response\.json\(\{([\s\S]*?)\}\)/);
  
  if (textMatch) {
    responseType = 'text';
    responseBody = textMatch[1];
  } else if (jsonMatch) {
    responseType = 'json';
    // Parse the simple key-value pairs
    const pairs = jsonMatch[1].split(',').map(p => {
      const [k, v] = p.split(':').map(s => s.trim());
      return { key: k, value: v.replace(/"/g, '') };
    });
    responseBody = pairs;
  }
  
  routes.push({ method, path, reqParam, responseType, responseBody });
}

console.log(`  ✓ Parsed: module=${moduleName}, port=${port}, routes=${routes.length}`);

// ── Generate Rust ────────────────────────────────────────

function generateRouteHandler(route, index) {
  const fnName = `handler_${index}`;
  
  if (route.responseType === 'text') {
    return `async fn ${fnName}() -> impl IntoResponse {
    "${route.responseBody}"
}`;
  }
  
  if (route.responseType === 'json') {
    const jsonObj = route.responseBody.map(p => `        "${p.key}": "${p.value}"`).join(',\n');
    return `async fn ${fnName}() -> impl IntoResponse {
    Json(serde_json::json!({
${jsonObj}
    }))
}`;
  }
  
  return `async fn ${fnName}() -> impl IntoResponse {
    "unhandled"
}`;
}

function generateRouterLine(route, index) {
  const fnName = `handler_${index}`;
  return `        .route("${route.path}", ${route.method}(${fnName}))`;
}

const needsJson = routes.some(r => r.responseType === 'json');

const jsonImports = needsJson ? `use axum::{
    routing::get,
    Router,
    response::IntoResponse,
    Json,
};
use serde_json;` : `use axum::{
    routing::get,
    Router,
    response::IntoResponse,
};`;

const rustCode = `// ┌────────────────────────────────────────────────┐
// │  Auto-generated by AID PoC Transpiler           │
// │  Source: ${aidFile.padEnd(39)}│
// │  Do not edit — regenerated on each build        │
// └────────────────────────────────────────────────┘

${jsonImports}
use tokio::net::TcpListener;

${routes.map((r, i) => generateRouteHandler(r, i)).join('\n\n')}

#[tokio::main]
async fn main() {
    let app = Router::new()
${routes.map((r, i) => generateRouterLine(r, i)).join('\n')};

    let addr = format!("0.0.0.0:${port}");
    println!();
    println!("  ╔═══════════════════════════════════════════╗");
    println!("  ║        🚀 AID Server Running              ║");
    println!("  ║                                           ║");
    println!("  ║   → http://localhost:${port}                  ║");
    println!("  ║   → Press Ctrl+C to stop                  ║");
    println!("  ╚═══════════════════════════════════════════╝");
    println!();

    let listener = TcpListener::bind(&addr).await.unwrap();
    axum::serve(listener, app).await.unwrap();
}
`;

const cargoToml = `[package]
name = "aid-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
`;

// ── Write output ─────────────────────────────────────────

const rustDir = resolve(outDir);
mkdirSync(resolve(rustDir, 'src'), { recursive: true });
writeFileSync(resolve(rustDir, 'Cargo.toml'), cargoToml);
writeFileSync(resolve(rustDir, 'src/main.rs'), rustCode);

console.log(`  ✓ Generated Rust project at ${rustDir}`);
console.log(`    • Cargo.toml`);
console.log(`    • src/main.rs`);

// ── Generate docs ────────────────────────────────────────

const docsDir = resolve(outDir, '..', 'docs');
mkdirSync(docsDir, { recursive: true });

const docsContent = `# ${moduleName} — Auto-Generated Documentation

*Generated by AID compiler on ${new Date().toISOString().split('T')[0]}*

## Routes

| Method | Path | Response Type |
|--------|------|---------------|
${routes.map(r => `| \`${r.method.toUpperCase()}\` | \`${r.path}\` | ${r.responseType} |`).join('\n')}

## Server Configuration

- **Port:** ${port}
- **Host:** 0.0.0.0

## Build Info

- **AID Source:** \`${aidFile}\`
- **Transpiled to:** Rust + Axum
- **Target:** Native binary (WASM planned)
`;

writeFileSync(resolve(docsDir, 'api.md'), docsContent);
console.log(`  ✓ Documentation generated at ${docsDir}/api.md`);
